// Curated Manhattan landmarks. Each entry is hand-written for accuracy.
// `coords` is [lng, lat]. `era` maps to the card theme (see style.css .card--<era>).

export const ERA_BY_ID = {
  'empire-state': 'artdeco',
  'chrysler': 'artdeco',
  'flatiron': 'beauxarts',
  'grand-central': 'beauxarts',
  'woolworth': 'gothic',
  'rockefeller': 'artdeco',
  'one-wtc': 'contemporary',
  'brooklyn-bridge': 'victorian',
  'manhattan-bridge': 'beauxarts',
  'williamsburg-bridge': 'victorian',
  'queensboro-bridge': 'beauxarts',
  'gw-bridge': 'modernist',
  'verrazzano-bridge': 'modernist',
  'statue-liberty': 'victorian',
  'guggenheim': 'modernist',
  'met-museum': 'beauxarts',
  'moma': 'modernist',
  'seagram': 'modernist',
  'lever-house': 'modernist',
  'dakota': 'victorian',
  'apollo': 'theatrical',
  'st-patricks': 'gothic',
  'washington-square-arch': 'beauxarts',
  'high-line': 'contemporary',
  'radio-city': 'artdeco',
  'plaza-hotel': 'beauxarts',
  'carnegie-hall': 'victorian',
  'nypl-main': 'beauxarts',
  'washington-square-park': 'victorian',
  'penn-station': 'modernist',
  'tenement-museum': 'victorian'
};

export const LANDMARKS = [
  {
    id: 'empire-state',
    name: 'Empire State Building',
    bin: 1015862,
    coords: [-73.9857, 40.7484],
    year: 1931,
    architect: 'Shreve, Lamb & Harmon',
    style: 'Art Deco',
    height: '381 m (1,250 ft) · 102 floors',
    history: 'Completed in just 410 days during the Great Depression, the Empire State Building was the world\'s tallest for nearly 40 years until the World Trade Center surpassed it in 1970. It was built on the site of the original Waldorf-Astoria Hotel, which was demolished to make way for it. For decades its upper floors stood largely empty — critics dubbed it the "Empty State Building" — but its spire, lights, and silhouette made it an immediate American icon.',
    design: 'A textbook example of setback Art Deco skyscraper design. The building steps back dramatically as it rises to comply with the 1916 Zoning Resolution. Limestone and granite facade with aluminum trim and distinctive vertical window bands. The spire was originally designed as a dirigible mooring mast — a plan quickly abandoned after one terrifying test.',
    fact: 'In 1945 a B-25 bomber lost in fog crashed into the 79th floor. Elevator operator Betty Lou Oliver survived a 75-story plunge when the cables snapped — still the Guinness record for longest survived elevator fall.'
  },
  {
    id: 'chrysler',
    name: 'Chrysler Building',
    bin: 1036156,
    coords: [-73.9754, 40.7516],
    year: 1930,
    architect: 'William Van Alen',
    style: 'Art Deco',
    height: '319 m (1,046 ft) · 77 floors',
    history: 'Built during a frenzied race with the Bank of Manhattan Building to become the world\'s tallest. Van Alen secretly assembled a 125-ft stainless-steel spire inside the fire shaft and hoisted it into place in just 90 minutes, vaulting past his rival. It held the title for only 11 months before the Empire State surpassed it. Walter Chrysler paid for the building personally so it would pass to his children.',
    design: 'The most beloved Art Deco skyscraper in the world. Seven tiered crowns of stainless steel with triangular windows create the unmistakable sunburst. Eagle gargoyles at the 61st floor are modeled after 1929 Chrysler hood ornaments. Hubcap-and-fender motifs decorate the brickwork. The lobby — African red marble, a painted ceiling mural, chrome steel — is a cathedral to the machine age.',
    fact: 'Van Alen was never paid his fee. Chrysler accused him of taking kickbacks from contractors, and the architect\'s career never fully recovered.'
  },
  {
    id: 'flatiron',
    bin: 1016278,
    name: 'Flatiron Building',
    coords: [-73.9897, 40.7411],
    year: 1902,
    architect: 'Daniel Burnham',
    style: 'Beaux-Arts',
    height: '87 m (285 ft) · 22 floors',
    history: 'Originally the Fuller Building, New Yorkers nicknamed it "the Flatiron" for its resemblance to a cast-iron clothing iron. At 22 stories it was one of the tallest in the city when it opened, and crowds gathered to watch, convinced the wedge-shaped building would topple. The wind whipping around its base was so strong it lifted women\'s skirts — the origin of the phrase "23 skidoo," which police used to shoo away men who loitered to watch.',
    design: 'A steel-frame skyscraper clad in limestone and terra-cotta in the Beaux-Arts Renaissance Revival style. The triangular footprint (wedged between Broadway, Fifth Ave, and 23rd St) is only 6.5 ft wide at its narrowest point. The facade is layered like a classical column — base, shaft, capital — with elaborate Beaux-Arts ornament.',
    fact: 'Alfred Stieglitz\'s 1903 photograph of the Flatiron in a snowstorm is considered one of the most important photos in American history.'
  },
  {
    id: 'grand-central',
    bin: 1035381,
    name: 'Grand Central Terminal',
    coords: [-73.9772, 40.7527],
    year: 1913,
    architect: 'Reed & Stem; Warren & Wetmore',
    style: 'Beaux-Arts',
    height: '51 m (168 ft)',
    history: 'The current terminal replaced two earlier stations after a 1902 crash in the smoke-filled Park Avenue tunnel killed 17 people and prompted the ban of steam locomotives in Manhattan. The air rights sold above the tracks funded decades of Midtown development — essentially creating Park Avenue as we know it. In the 1960s it was nearly demolished for a tower; Jacqueline Kennedy Onassis led the campaign that saved it and established modern US historic preservation law.',
    design: 'The Main Concourse — 275 ft long, 125 ft tall — is one of the great civic rooms of the world. The famous teal ceiling depicts the zodiac, painted backwards (likely from a medieval manuscript that showed the sky "as seen by God"). The four-faced brass clock atop the information booth is valued at $10-20 million. Guastavino tile vaults line the Oyster Bar, enabling the famous "whispering gallery."',
    fact: 'A hidden sub-basement, M42, housed the rotary converters that powered the entire terminal. During WWII it was so strategically important that guards were ordered to shoot intruders on sight.'
  },
  {
    id: 'woolworth',
    bin: 1087167,
    name: 'Woolworth Building',
    coords: [-74.0083, 40.7124],
    year: 1913,
    architect: 'Cass Gilbert',
    style: 'Neo-Gothic',
    height: '241 m (792 ft) · 57 floors',
    history: 'F.W. Woolworth paid the $13.5 million construction cost in cash from the profits of his five-and-dime empire. At completion it was the tallest building in the world (surpassing the Met Life Tower) and held that title until 1930. President Woodrow Wilson lit the building\'s 80,000 bulbs by pressing a button in Washington D.C. It was dubbed the "Cathedral of Commerce" for its ecclesiastical style.',
    design: 'A Gothic cathedral reimagined as a skyscraper — flying buttresses, gargoyles, pointed arches, and a green copper pyramid crown. The terracotta facade is cream at the base, shading lighter as it rises to emphasize height. The lobby is a Byzantine-Romanesque jewel box with gold-leaf ceilings, marble walls, and satirical gargoyles depicting Woolworth counting his dimes and Gilbert hugging a model of the building.',
    fact: 'Woolworth insisted his new building be exactly 50 feet taller than the Metropolitan Life Tower, then the world\'s tallest.'
  },
  {
    id: 'rockefeller',
    bin: 1076262,
    name: '30 Rockefeller Plaza',
    coords: [-73.9787, 40.7587],
    year: 1933,
    architect: 'Raymond Hood; Associated Architects',
    style: 'Art Deco',
    height: '259 m (850 ft) · 70 floors',
    history: 'John D. Rockefeller Jr. originally leased the site to build a new Metropolitan Opera House. The 1929 crash killed that plan — but Rockefeller was locked into a 24-year lease, so he decided to build a "city within a city" himself. The Depression-era megaproject employed 40,000 workers. Its completion in 1933 was marked by the first Christmas tree, and NBC\'s Radio City Music Hall opened the same year.',
    design: 'A slab-shaped Art Deco masterpiece — limestone, aluminum, and thousands of operable windows. The facade is rigorously stripped of ornament except at setbacks and the iconic Lee Lawrie "Wisdom" relief above the entrance. The integrated plaza, skating rink, and Prometheus sculpture pioneered the "urban complex" that shaped later American cities.',
    fact: 'The famous 1932 "Lunch atop a Skyscraper" photograph — 11 ironworkers eating on a beam 850 ft up — was taken during construction of 30 Rock and was a staged publicity shot.'
  },
  {
    id: 'one-wtc',
    bin: 1088469,
    name: 'One World Trade Center',
    coords: [-74.0134, 40.7127],
    year: 2014,
    architect: 'David Childs (SOM)',
    style: 'Structural Expressionism',
    height: '541 m (1,776 ft) · 94 floors',
    history: 'Built to replace the Twin Towers destroyed on September 11, 2001. Its final height of 1,776 ft is a deliberate reference to the year of American independence. Construction was fraught with political, security, and design conflicts spanning 13 years. It is the tallest building in the Western Hemisphere.',
    design: 'A tapering obelisk with eight isoceles triangular faces that rotate 45° from base to crown, so the building appears to shift form as you move around it. The 186-ft base is a blast-resistant concrete bunker clad in glass prisms. The spire is a communications mast designed to evoke the Statue of Liberty\'s torch.',
    fact: 'The observation deck elevators rise 1,250 ft in 60 seconds — and the walls show a time-lapse of NYC\'s skyline growing from 1500 to the present during the ride.'
  },
  {
    id: 'brooklyn-bridge',
    name: 'Brooklyn Bridge',
    coords: [-73.9969, 40.7061],
    year: 1883,
    architect: 'John A. Roebling; Washington Roebling; Emily Warren Roebling',
    style: 'Neo-Gothic suspension',
    height: 'Towers: 84 m (276 ft) · Span: 486 m',
    history: 'The world\'s first steel-wire suspension bridge and, for 20 years, the longest. John Roebling died of tetanus from a foot injury sustained while surveying. His son Washington took over, but was crippled by caisson disease ("the bends") from working in the underwater foundations. His wife Emily Warren Roebling secretly ran the project for 11 years — studying engineering in her husband\'s sickroom — and was the first person to cross the completed bridge.',
    design: 'Two limestone-and-granite Gothic towers with pointed arches anchor four massive steel cables. The cables are woven from 5,434 parallel wires each. The bridge deck carries pedestrians on an elevated wooden promenade above the traffic — a deliberate gift from Roebling to the public.',
    fact: 'Six days after opening, a panic stampede killed 12 pedestrians. A year later P.T. Barnum marched 21 elephants across to prove it was safe.'
  },
  {
    id: 'manhattan-bridge',
    name: 'Manhattan Bridge',
    coords: [-73.9905, 40.7075],
    year: 1909,
    architect: 'Leon Moisseiff',
    style: 'Beaux-Arts suspension',
    height: 'Towers: 102 m (336 ft) · Span: 448 m',
    history: 'The third suspension bridge across the East River, opened just 26 years after the Brooklyn Bridge. Moisseiff used a then-radical "deflection theory" that allowed lighter, more flexible suspension bridges — the same approach was later blamed for the catastrophic Tacoma Narrows collapse in 1940. The Manhattan-side approach is a Beaux-Arts triumphal arch and colonnade by Carrère & Hastings (also of NYPL fame).',
    design: 'Two steel towers carry four cables; the deck has subway tracks on the lower level and roadway above — making it one of the few NYC bridges still carrying heavy rail transit. The Manhattan portal at Canal Street and Bowery is a grand Beaux-Arts gateway with a sweeping colonnade.',
    fact: 'When the bridge first opened, the lower deck flexed alarmingly under subway trains. Engineers had to retrofit it with extra trusses in the 1940s and again in the 1980s — the latter took 22 years and over a billion dollars to complete.'
  },
  {
    id: 'williamsburg-bridge',
    name: 'Williamsburg Bridge',
    coords: [-73.9722, 40.7137],
    year: 1903,
    architect: 'Leffert L. Buck; Henry Hornbostel',
    style: 'Steel suspension',
    height: 'Towers: 94 m (310 ft) · Span: 488 m',
    history: 'When it opened in December 1903, it was the longest suspension bridge in the world, narrowly beating the Brooklyn Bridge. It became the artery for tens of thousands of Lower East Side immigrants moving to Williamsburg, transforming both neighborhoods almost overnight — Williamsburg\'s population quadrupled in a decade.',
    design: 'Unlike the Brooklyn Bridge\'s ornamental Gothic stone towers, Williamsburg\'s towers are unapologetic exposed steel — a deliberate statement of industrial modernism. The bridge carries roadway, subway (J/M/Z), pedestrian, and cycling decks. Its raw steel aesthetic was controversial at the time but is now considered an early modernist landmark.',
    fact: 'The bridge had to be closed in 1988 after rust and cable corrosion were found to be near-catastrophic. The full repair took until 2002 and cost more than the bridge\'s entire original construction budget.'
  },
  {
    id: 'queensboro-bridge',
    name: 'Queensboro Bridge (Ed Koch Bridge)',
    coords: [-73.9543, 40.7572],
    year: 1909,
    architect: 'Gustav Lindenthal; Henry Hornbostel',
    style: 'Cantilever truss',
    height: 'Towers: 107 m (350 ft) · Span: 360 m main',
    history: 'A two-level cantilever steel bridge connecting Manhattan and Queens via Roosevelt Island in the middle. Featured in the famous "I love this dirty town" scene in Woody Allen\'s Manhattan and on the cover of Simon & Garfunkel\'s 59th Street Bridge Song. The 59th Street name comes from where it lands in Manhattan; the official name is now the Ed Koch Queensboro Bridge.',
    design: 'Unusual double-deck cantilever design — no suspension cables. The truss work creates a distinctive lattice silhouette. The lower-deck arches once carried trolleys and a tram station that served Roosevelt Island until the dedicated tram opened in 1976.',
    fact: 'There are abandoned trolley platforms inside the bridge\'s anchorages on the Manhattan side that were forgotten for decades. They now serve as service rooms — but the original cathedral-like vaulted spaces underneath the bridge approach are sometimes opened for events and are quietly one of the most beautiful interiors in the city.'
  },
  {
    id: 'gw-bridge',
    name: 'George Washington Bridge',
    coords: [-73.9525, 40.8517],
    year: 1931,
    architect: 'Othmar Ammann; Cass Gilbert (architectural consultant)',
    style: 'Steel suspension',
    height: 'Towers: 184 m (604 ft) · Span: 1,067 m',
    history: 'The world\'s longest suspension bridge for four years (until the Golden Gate opened in 1937). Othmar Ammann\'s elegant engineering carried more lanes than any prior bridge, fundamentally restructuring traffic between New Jersey and the city. A second deck — the lower "Martha Washington" deck — was added in 1962, doubling capacity.',
    design: 'Originally Cass Gilbert designed ornate stone cladding for the towers, but the project ran out of money during the Depression and the bare steel skeleton was left exposed. Le Corbusier called the result "the most beautiful bridge in the world," precisely because of that accidental modernist honesty.',
    fact: 'Each main cable contains 26,474 individual steel wires bundled into 61 strands. If unspooled and laid end to end, the wires from one cable would stretch from New York to Tokyo and back.'
  },
  {
    id: 'verrazzano-bridge',
    name: 'Verrazzano-Narrows Bridge',
    coords: [-74.0445, 40.6066],
    year: 1964,
    architect: 'Othmar Ammann',
    style: 'Steel suspension',
    height: 'Towers: 211 m (693 ft) · Span: 1,298 m',
    history: 'When opened in 1964, it was the longest suspension bridge span in the world — a record it held for 17 years. Connecting Brooklyn and Staten Island, it transformed Staten Island from a relatively rural outer borough into a fully connected part of the city, and is famously the starting line for the NYC Marathon. Named for Giovanni da Verrazzano, the first European to enter New York Harbor in 1524.',
    design: 'Othmar Ammann\'s last great work, completed when he was 85. The towers are so tall and the span so long that the engineers had to account for the curvature of the Earth — the tops of the two towers are 1 5/8" farther apart than the bases.',
    fact: 'For decades the official name was misspelled "Verrazano" with one z. New York State formally corrected it to "Verrazzano" in 2018 to match the explorer\'s actual surname.'
  },
  {
    id: 'statue-liberty',
    name: 'Statue of Liberty',
    coords: [-74.0445, 40.6892],
    year: 1886,
    architect: 'Frédéric Auguste Bartholdi; Gustave Eiffel (interior)',
    style: 'Neoclassical / Beaux-Arts',
    height: '93 m (305 ft) overall · 46 m statue · 47 m pedestal',
    history: 'A gift from the people of France commemorating the centennial of American independence and the abolition of slavery. Bartholdi sculpted the copper skin; Gustave Eiffel — yes, that Eiffel — engineered the wrought-iron skeleton that lets the statue flex in the wind without cracking. The pedestal was funded by a public penny-drive run by Joseph Pulitzer in the New York World, after Congress and the state refused to pay. She was originally a dull copper color; the famous green patina took about 30 years to develop.',
    design: 'The statue stands on a star-shaped fort (Fort Wood, built 1808–1811) topped by an 89-foot Beaux-Arts pedestal of granite and concrete designed by Richard Morris Hunt. Inside, Eiffel\'s iron pylon supports the 31-ton copper skin, which is only 3/32" thick — about the thickness of two pennies stacked. The seven rays of the crown represent the seven seas and seven continents.',
    fact: 'The torch you see today is not the original. The original 1886 torch was modified so many times that by the 1980s it leaked. It was replaced in 1986 with a new gilded copper flame, and the original is now displayed in the museum at the base.'
  },
  {
    id: 'guggenheim',
    bin: 1046946,
    name: 'Solomon R. Guggenheim Museum',
    coords: [-73.9589, 40.7830],
    year: 1959,
    architect: 'Frank Lloyd Wright',
    style: 'Modernist / Organic',
    height: '29 m (96 ft)',
    history: 'Wright\'s only NYC building. Commissioned in 1943 and agonized over for 16 years; Wright died six months before it opened. Hilla Rebay, the museum\'s first director, wanted a "temple of the spirit" for non-objective art. 21 artists (including Willem de Kooning) signed a letter protesting that the building would overpower the art. It opened to enormous controversy and is now itself one of the world\'s most famous works of architecture.',
    design: 'An inverted concrete ziggurat — a continuous quarter-mile spiral ramp winding upward around a central atrium crowned by a glass dome. Wright intended visitors to take the elevator up, then stroll downward viewing paintings against gently curving walls tilted backward like an easel. The pure white exterior form is completely unlike anything else on Fifth Avenue.',
    fact: 'Wright fought the NYC Building Department on 32 design points. He won most of them by threatening to resign, then suing.'
  },
  {
    id: 'met-museum',
    bin: 1083810,
    name: 'The Metropolitan Museum of Art',
    coords: [-73.9632, 40.7794],
    year: 1880,
    architect: 'Calvert Vaux; Jacob Wrey Mould; later Richard Morris Hunt; McKim, Mead & White',
    style: 'Beaux-Arts (primary facade)',
    height: '5 floors',
    history: 'Founded in 1870 by a group of businessmen and artists who wanted to bring art to the American people. Opened in a temporary building downtown before moving to its current Central Park site in 1880. The original High Victorian Gothic structure by Vaux is now entirely encased inside later additions. The Fifth Avenue facade most people know was Richard Morris Hunt\'s 1902 Beaux-Arts frontage.',
    design: 'Hunt\'s facade is a triumphant arch-and-column composition in limestone, with four pairs of unfinished pediment blocks that were never carved — supposedly because the sculptor died before completing the work, though they\'ve become an accepted part of the design. The Great Hall domed entry is 60 ft high, a generous gesture of welcome.',
    fact: 'The Met\'s "suggested admission" ($25 today) was created in 1970; before that entry was free. Many New Yorkers still pay $1.'
  },
  {
    id: 'moma',
    bin: 1081128,
    name: 'Museum of Modern Art',
    coords: [-73.9776, 40.7614],
    year: 1939,
    architect: 'Philip L. Goodwin; Edward Durell Stone (orig.); Yoshio Taniguchi (2004); Diller Scofidio + Renfro (2019)',
    style: 'International Style (orig.); Contemporary',
    height: '6 floors',
    history: 'Founded in 1929 — nine days after the Wall Street crash — by Abby Aldrich Rockefeller and two friends, who believed America needed a museum for the new modern art Europe was producing. The 1939 Goodwin & Stone building was the first fully International Style public building in the US. Expanded multiple times since; the 2004 Taniguchi rebuild gutted most prior interiors for a stark minimalist reboot.',
    design: 'The 1939 facade was radical: flat marble-and-glass with no ornament, no symmetry, and a ribbon window — a manifesto for modern architecture. Taniguchi\'s 2004 atrium is 110 ft tall and pushes the galleries toward light, air, and silence. The 2019 expansion by DS+R added flexible "studio" galleries and opened the lower floor to the street.',
    fact: 'In 1958 a fire on the second floor destroyed a Monet Water Lilies and forced evacuation of the collection through the streets by hand.'
  },
  {
    id: 'seagram',
    bin: 1036465,
    name: 'Seagram Building',
    coords: [-73.9719, 40.7586],
    year: 1958,
    architect: 'Ludwig Mies van der Rohe; Philip Johnson',
    style: 'International Style',
    height: '157 m (515 ft) · 38 floors',
    history: 'Commissioned by Phyllis Lambert, 27-year-old daughter of Seagram\'s CEO, who rejected her father\'s chosen architect and insisted on Mies. It became the most influential corporate tower of the 20th century — the reference point for every glass box that followed — and pioneered the setback plaza as gift to the public. The ground-floor Four Seasons restaurant (now closed) was the invention of the "power lunch."',
    design: 'A bronze-and-bronze-glass curtain wall of such precision it reads almost like a sculpture. Mies insisted on fixed-position window blinds (three positions only) so the facade would always look ordered. The 90-ft granite plaza in front, empty of ornament, changed NYC zoning forever when the city began offering floor-area bonuses for public plazas.',
    fact: 'The I-beams on the facade are decorative — purely applied to express a structure that\'s actually hidden behind fireproofing. Mies called this the "honest expression of construction," a line critics have argued with ever since.'
  },
  {
    id: 'lever-house',
    bin: 1035732,
    name: 'Lever House',
    coords: [-73.9724, 40.7593],
    year: 1952,
    architect: 'Gordon Bunshaft (SOM)',
    style: 'International Style',
    height: '94 m (307 ft) · 21 floors',
    history: 'The first glass-curtain-wall skyscraper on Park Avenue and the building that made the International Style the American corporate norm. Commissioned by Lever Brothers (the soap company); Bunshaft designed the glass to be washed constantly — a pun on the client\'s product. Its radical setback from the street, leaving an open plaza beneath, was unprecedented for Park Avenue and inspired the 1961 NYC zoning changes.',
    design: 'A horizontal slab on top of a vertical slab, the whole thing elevated on pilotis. The blue-green heat-absorbing glass was an industry first. Only 25% of the lot was built on — a shocking inefficiency that Lever chose for the prestige of the public plaza.',
    fact: 'The lobby held a single rotating sculpture, swapped quarterly. Today the tradition continues — major artists install work in the plaza.'
  },
  {
    id: 'dakota',
    bin: 1028637,
    name: 'The Dakota',
    coords: [-73.9763, 40.7764],
    year: 1884,
    architect: 'Henry Janeway Hardenbergh',
    style: 'German Renaissance Revival',
    height: '9 floors',
    history: 'When it opened on the edge of Central Park, the neighborhood was so undeveloped that New Yorkers joked it was "as far away as Dakota Territory" — hence the name, which stuck. It was one of the first luxury apartment buildings in a city where wealthy people still lived in single-family homes; the building\'s success helped normalize apartment living for the upper class. John Lennon was shot and killed at its gate on December 8, 1980.',
    design: 'A dense, picturesque massing of German Renaissance forms — gables, dormers, balconies, niches, and elaborate ironwork — clad in buff brick, terra-cotta, and sandstone. The central courtyard, reached through a grand arched carriage entrance, was designed to feel like a medieval European hôtel particulier.',
    fact: 'Rosemary\'s Baby (1968) used the Dakota as the Bramford. Residents have included Leonard Bernstein, Lauren Bacall, Judy Garland, and Boris Karloff.'
  },
  {
    id: 'apollo',
    bin: 1058654,
    name: 'Apollo Theater',
    coords: [-73.9503, 40.8099],
    year: 1914,
    architect: 'George Keister',
    style: 'Neo-Classical',
    height: '4 floors',
    history: 'Opened in 1914 as Hurtig & Seamon\'s New Burlesque Theater — whites-only. Mayor LaGuardia shut down burlesque in the 1930s, and in 1934 new owners reopened it as the Apollo, welcoming Black audiences and performers. Amateur Night — launched 1934 and still running — discovered Ella Fitzgerald (age 17), James Brown, Stevie Wonder, Lauryn Hill, and countless others. It was the most important Black cultural venue in America for most of the 20th century.',
    design: 'A modest Neo-Classical facade with its signature red-and-gold marquee (added later). The interior is a 1,506-seat proscenium theater with intimate sightlines — small enough that every seat feels close to the stage, which is considered essential to the legendary Apollo audience-performer dynamic.',
    fact: 'The "Tree of Hope" stump backstage, a fragment of an elm that once stood on 7th Avenue, is rubbed for luck by every performer before going on.'
  },
  {
    id: 'st-patricks',
    bin: 1081149,
    name: 'St. Patrick\'s Cathedral',
    coords: [-73.9760, 40.7585],
    year: 1879,
    architect: 'James Renwick Jr.',
    style: 'Neo-Gothic',
    height: '100 m (330 ft) spires',
    history: 'When construction began in 1858, the Fifth Avenue site was considered absurdly far uptown — rural, really — and the project was ridiculed as "Hughes\' Folly" (after Archbishop John Hughes). By the time it was consecrated in 1879 it stood at the heart of Gilded Age Manhattan. The spires were added in 1888. It remains the largest Gothic Revival Catholic cathedral in the US.',
    design: 'A French Gothic cathedral — pointed arches, flying buttresses, rose windows, twin 330-ft spires — built of Tuckahoe marble. The interior holds over 3,000 worshippers beneath a ribbed vaulted ceiling, with 19 side altars and some of the largest church-organ installations in the country. The bronze doors weigh 20,000 lb.',
    fact: 'The 2012-2015 restoration removed 150 years of candle soot and grime, returning the exterior to its original glowing white.'
  },
  {
    id: 'washington-square-arch',
    name: 'Washington Square Arch',
    coords: [-73.9974, 40.7308],
    year: 1895,
    architect: 'Stanford White',
    style: 'Beaux-Arts / Roman Triumphal',
    height: '23 m (77 ft)',
    history: 'Originally erected in 1889 as a temporary wood-and-plaster arch to celebrate the centennial of George Washington\'s inauguration. It was so popular that a permanent marble version was commissioned. On a snowy night in January 1917, a group of artists including Marcel Duchamp climbed to the top, built a bonfire, and declared Greenwich Village a "free and independent republic."',
    design: 'Modeled on the Arc de Triomphe, in Tuckahoe marble. Two large sculptural groups on the north face — "Washington at War" (Hermon MacNeil, 1916) and "Washington at Peace" (A. Stirling Calder, 1918) — frame the central span. The spandrels carry winged figures of Fame and Valor.',
    fact: 'A full-scale crypt is hidden inside the arch, accessed through a door on the west pier. A spiral stair leads to the roof.'
  },
  {
    id: 'high-line',
    name: 'The High Line',
    coords: [-74.0048, 40.7480],
    year: 2009,
    architect: 'James Corner Field Operations; Diller Scofidio + Renfro; Piet Oudolf (planting)',
    style: 'Adaptive reuse / Landscape urbanism',
    height: 'Elevated 9 m above street',
    history: 'A 1930s freight rail viaduct running 1.45 miles from the Meatpacking District to Hudson Yards. Abandoned in 1980, it grew wild with self-seeded plants. Mayor Giuliani wanted it demolished. In 1999 neighborhood residents Joshua David and Robert Hammond founded Friends of the High Line and fought for years to save it. Opened in sections from 2009 to 2019. It sparked a global movement of derelict infrastructure reuse and massively gentrified the surrounding neighborhoods.',
    design: 'The original rail tracks are preserved in the hardscape; planting beds follow the "self-seeded" aesthetic of the abandoned railway, designed by Oudolf to look wild but peak through the seasons. Viewing decks, amphitheater-seating over 10th Avenue, and a central "flyover" through a tree canopy create a sequence of choreographed urban moments.',
    fact: 'Over 8 million people visit annually — more than the Statue of Liberty. The project cost $260 million but generated an estimated $2 billion in surrounding property value.'
  },
  {
    id: 'radio-city',
    bin: 1083861,
    name: 'Radio City Music Hall',
    coords: [-73.9799, 40.7599],
    year: 1932,
    architect: 'Edward Durell Stone; Donald Deskey (interior)',
    style: 'Art Deco',
    height: '6 floors · 5,960 seats',
    history: 'Part of Rockefeller Center. It was briefly the world\'s largest indoor theater. Impresario Samuel "Roxy" Rothafel imagined it as a grand palace of variety shows; the opening-night program in 1932 was a 5-hour disaster that sent critics fleeing. The pivot to movies-plus-stage-shows saved it, and the Rockettes (formed as "The Missouri Rockets" in St. Louis in 1925, reborn here) became the permanent draw.',
    design: 'The auditorium\'s golden proscenium is modeled on a sunset, with concentric arched bands receding to the stage — often called the "most beautiful interior in America." Donald Deskey designed every detail: Bakelite, cork, aluminum leaf, a signature palette of golds and reds. The stage has three movable sections with elevators, an 11-ton orchestra lift, and a ceiling-hung lighting bridge that was the most advanced of its era.',
    fact: 'The Mighty Wurlitzer organ has 4,410 pipes in 11 tone chambers and is played live before every Christmas Spectacular.'
  },
  {
    id: 'plaza-hotel',
    bin: 1035253,
    name: 'The Plaza Hotel',
    coords: [-73.9743, 40.7646],
    year: 1907,
    architect: 'Henry Janeway Hardenbergh',
    style: 'French Renaissance chateau',
    height: '76 m (250 ft) · 21 floors',
    history: 'Hardenbergh\'s second NYC masterpiece after the Dakota. It replaced an earlier Plaza Hotel on the same site. It has been the center of NYC high society since opening — home at various times to Frank Lloyd Wright, F. Scott Fitzgerald, the Beatles\' first American stay, and the fictional Eloise. In 1985 Donald Trump bought it for $390 million and nearly bankrupted it; it has changed hands multiple times since and is now partly condos.',
    design: 'A French Renaissance chateau scaled up to a Fifth Avenue hotel — mansard roof, dormers, gabled pavilions, white-glazed brick with limestone and terra-cotta trim. The Palm Court lobby is covered by a stained-glass skylight that was removed in the 1940s and restored in the 2000s.',
    fact: 'The Plaza hosted Truman Capote\'s 1966 Black and White Ball in its Grand Ballroom — widely called "the Party of the Century."'
  },
  {
    id: 'carnegie-hall',
    bin: 1023449,
    name: 'Carnegie Hall',
    coords: [-73.9800, 40.7650],
    year: 1891,
    architect: 'William Burnet Tuthill',
    style: 'Italian Renaissance Revival',
    height: '6 floors',
    history: 'Funded by Andrew Carnegie. Tchaikovsky conducted his own music at the opening-week concerts in 1891. Nearly demolished in 1960 for a commercial tower; violinist Isaac Stern led the campaign that saved it, and the resulting "Carnegie Hall Corporation" became the model for city-owned arts venues across America. The Stern Auditorium\'s acoustics — shoebox shape, no right angles, horsehair-and-plaster walls — remain among the most celebrated in the world.',
    design: 'A restrained Italian Renaissance Revival facade in brown brick and terra-cotta, quiet on the outside so the auditorium can do the talking. The architect was not a professional: Tuthill was an amateur cellist and acoustician whose design was chosen for its acoustic thinking. Five curved balconies float above the stalls without visible columns.',
    fact: 'The old joke — "How do you get to Carnegie Hall? Practice, practice, practice" — is attributed to violinist Jascha Heifetz or pianist Arthur Rubinstein (depending on who\'s telling it).'
  },
  {
    id: 'nypl-main',
    bin: 1034194,
    name: 'New York Public Library (Main Branch)',
    coords: [-73.9822, 40.7532],
    year: 1911,
    architect: 'Carrère and Hastings',
    style: 'Beaux-Arts',
    height: '5 floors',
    history: 'Built on the site of the former Croton Reservoir. Officially named the Stephen A. Schwarzman Building in 2008. At the time of opening, its Rose Main Reading Room was the largest uncolumned room in the world. The library was the first in America to operate on a "closed stack" system where books were paged up by pneumatic tube. Its two marble lions — Patience and Fortitude, named by Mayor LaGuardia in the Depression — have become NYC mascots.',
    design: 'The apex of American Beaux-Arts — pale Vermont marble, flanking fountains, a triumphal-arch facade, and a monumental ceremonial stair. The Rose Main Reading Room, 78 ft x 297 ft, has a 52-ft painted ceiling with trompe-l\'oeil sky panels. 88 miles of book stacks in the basement hold the collection.',
    fact: 'The seven-story stack system beneath the reading room was structural: the building\'s floors rest on the steel book-stack frame. When the stacks were moved out for modernization, the building had to be re-engineered.'
  },
  {
    id: 'washington-square-park',
    name: 'Washington Square Park',
    coords: [-73.9973, 40.7308],
    year: 1827,
    architect: 'George Vellonakis (current redesign, 2014)',
    style: 'Public park',
    height: '9.75 acres',
    history: 'Originally a Lenape hunting ground, then marshland, then a potter\'s field where an estimated 20,000 mostly poor and yellow-fever-victim bodies were buried. Converted to a military parade ground in 1826 and a public park the next year. The neighborhood around it became the cultural center of bohemian New York — the beats, folk revival, off-Broadway. Jane Jacobs led the 1950s fight against Robert Moses\' plan to run a highway through the park.',
    design: 'The current layout (2014 redesign) preserves the central fountain (realigned with the arch), Richard Morris Hunt\'s historic hedge rooms on the east, and a dog run on the south. The famous chess tables at the southwest corner have operated continuously since the 1930s.',
    fact: 'An estimated 20,000 bodies remain buried under the park. Construction projects routinely unearth skeletons; the last major find was in 2008.'
  },
  {
    id: 'penn-station',
    name: 'Penn Station',
    coords: [-73.9933, 40.7506],
    year: 1968,
    architect: 'Charles Luckman (current concourse); McKim, Mead & White (original 1910 head house, demolished 1963–66)',
    style: 'Beaux-Arts (original) · Modernist concrete (current)',
    height: 'Underground concourse · MSG above',
    history: 'Penn Station is the busiest transit hub in the Western Hemisphere, moving over 600,000 passengers a day across Amtrak, NJ Transit, and LIRR. The Penn Station you walk through today (opened 1968) is a low-ceilinged underground concourse beneath Madison Square Garden — built after the Pennsylvania Railroad demolished the original 1910 McKim, Mead & White head house, a Beaux-Arts cathedral modeled on the Baths of Caracalla. The destruction of the original was so traumatic that it directly produced NYC\'s 1965 Landmarks Preservation Law, which is why buildings like Grand Central could not be torn down a few years later. The 2021 Moynihan Train Hall, across the street in the old Farley Post Office, returned a small piece of grand Beaux-Arts railroad architecture to the site.',
    design: 'The current station is functional rather than ceremonial — most of the public concourse sits one or two stories below grade, beneath the Madison Square Garden arena and the 2 Penn Plaza office tower. The 2021 Moynihan Train Hall (Skidmore, Owings & Merrill) reuses the 1912 Farley Post Office across 8th Avenue and crowns the train shed with a 92-foot skylight, partly compensating for what was lost in 1963.',
    fact: '"One entered the city like a god; one scuttles in now like a rat," wrote architectural historian Vincent Scully about the original\'s loss. Pieces of the demolished 1910 station were used as landfill in the New Jersey Meadowlands. Several of the surviving stone eagles are now at Hicksville LIRR station and the Market Street Bridge in Cooperstown.'
  },
  {
    id: 'tenement-museum',
    bin: 1005474,
    name: '97 Orchard Street (Tenement Museum)',
    coords: [-73.9905, 40.7189],
    year: 1864,
    architect: 'Unknown',
    style: 'Italianate tenement',
    height: '5 floors',
    history: 'A typical 1864 Lower East Side tenement that housed an estimated 7,000 people from 20 countries over 72 years, until the landlord evicted everyone in 1935 rather than comply with new building codes. The building was effectively sealed, preserving the apartments in time-capsule condition. Rediscovered in 1988 and now the heart of the Lower East Side Tenement Museum — an unusual landmark that celebrates not wealth and design, but the lived experience of immigration.',
    design: 'Standard brick-bearing-wall construction with narrow windowless interior rooms — a layout the 1867 Tenement House Act was designed to stop. Each floor held four apartments sharing a hallway toilet; apartments averaged 325 sq ft and housed 6-10 people. The 1879 "dumbbell" plan (required by law after 1879) never reached 97 Orchard because it was already built.',
    fact: 'The museum\'s tours include recreated apartments furnished as specific historical families lived in them — the Baldizzis (Italian, 1935), the Rogarshevskys (Lithuanian-Jewish, 1918), the Levines (garment-shop family, 1897).'
  }
];
